language: java
install:
  - sudo apt-get install openjfx

os: linux
dist: focal
jdk: openjdk9

script:
   - gradle -Puser=stephanmg -Pkey=$BINTRAY_API_TOKEN jar
   - gradle -Puser=stephanmg -Pkey=$BINTRAY_API_TOKEN bundle
   
deploy:
  provider: script
  script: bash scripts/deploy.sh
