language: java
before_install:
  - sudo apt-get -y install openjfx
install:
  - skip

os: linux
dist: xenial
jdk: openjdk8

script:
   - wget https://services.gradle.org/distributions/gradle-6.6.1-bin.zip
   - unzip gradle-6.6.1-bin.zip
   - ./gradle-6.6.1/bin/gradle -Puser=stephanmg -Pkey=$BINTRAY_API_TOKEN jar
   - ./gradle-6.6.1/bin/gradle -Puser=stephanmg -Pkey=$BINTRAY_API_TOKEN bundle
   
deploy:
  provider: script
  script: bash scripts/deploy.sh
