language: java
install: skip

os: linux
dist: focal

script:
   - gradle -Puser=stephanmg -Pkey=$BINTRAY_API_TOKEN jar
   - gradle -Puser=stephanmg -Pkey=$BINTRAY_API_TOKEN bundle
   
deploy:
  provider: script
  script: bash scripts/deploy.sh
