name: CI

on:
  push:
    branches-ignore: gh-pages
  pull_request:
    branches-ignore: gh-pages

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Update 
        run: sudo apt-get update

      - name: Install JavaFX
        run: sudo apt-get -y install openjfx

      - name: "Setup JDK 1.8"
      - uses: joschi/setup-jdk@v2
        with:
          java-version: '8'
          architecture: 'x64' 

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Run the tests
        run: ./gradlew check

      - name: Create fat jar
        run: ./gradlew bundle

      - name: Upload fat jar
        uses: actions/upload-artifact@v2
        with:
          name: fat_jar
          path: build/libs/Solitaire.jar
